@startuml publish-flow

(*) -down-> "新しいブランチを作る"
-down-> "プルリクエストを作成する"
-down-> "記事を書く"
-down-> "記事をプッシュする"
if "GitHub Actionsで校正チェックを行う"
    -down-> [チェックが通る] "mainブランチにマージする"
        if "Zenn 上で目視で記事を見直す"
            --> [問題ない] "published: trueにする変更をmainブランチに加える"
            --> [記事が公開される] (*)
        else
            -up-> [問題ある] "記事を書く"
        endif
else
    -up-> [チェックが通らない] "記事を書く"
endif

@enduml
